version: 2
jobs:
  build:
    docker:
      - image: docker:18-git
    working_directory: ~/github-tools
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ruby/bin/run_all_tests.sh
